# Site title and subtitle. This is used in _includes/header.html
title: 'Random Thoughts'
subtitle: 'A wiki of my random thoughts.'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
google_analytics_id: 'UA-19545856-3'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'http://www.dgyblog.com/'

# Default categories (in order) to appear in the navigation
sections: [
    ['ml', 'Machine Learning'],
    ['ns', 'Neuroscience'],
    ['cs', 'Computer Science'],
    ['ref', 'References'],
    ['tut', 'Tutorial'],
    ['poj', 'Projects'],
    ['journal', 'Life Journal']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: ''

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
# highlighter: pygments

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the redcarpet Markdown renderer
#markdown: redcarpet
#pygments: true
markdown: kramdown
#highlighter: pygments

kramdown:
  math_engine: mathjax
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay:            true
  coderay_line_numbers:      nil
  coderay_line_number_start: 1
  coderay_tab_width:         4
  coderay_css:               style
  coderay_wrap:              div

#redcarpet:
#    extensions: [
#        'no_intra_emphasis',
#        'fenced_code_blocks',
#        'autolink',
#        'strikethrough',
#        'superscript',
#        'with_toc_data',
#        'tables',
##        'hardwrap'
#]